import Head from "next/head";
import Catalogue from "@/components/Catalogue";
import Navbar from "@/components/Navbar";
import Cart_Card from "@/components/CartCard";
import styles from "@/styles/Home.module.css";

export default function Cart({ products }) {
  return (
    <>
      <Head>
        <title>quartz. watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className="NavBar" products={products} />
        <Cart_Card products={products} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  // Get the filter value from the context
  // const filterValue = context.params?.filter ?? "";
  const res = await fetch("http://localhost:7000/cart/");
  const products = await res.json();

  return {
    props: {
      products,
    },
  };
}
