import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Product from '@/components/Product';
import Navbar from '@/components/Navbar';

export default function ProductPage({ products, product }) {
  return (
    <>
      <Head>
        <title>quartz. watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className="NavBar" products={products} />
        <Product product={product} />
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const { id } = context.params;

  const client = new ApolloClient({
    uri: 'http://localhost:4000/graphql',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetProduct($id: ID!) {
        products {
          id
          imageUrl
          name
          brandName
          groupId
          price {
            current {
              text
            }
          }
          features {
            BatteryCapacity
            BluetoothChip
            Material
            ScreenResolution
            ScreenSize
            StandBy
            Waterproof
          }
        }
        product(id: $id) {
          id
          imageUrl
          name
          brandName
          groupId
          price {
            current {
              text
            }
          }
          features {
            BatteryCapacity
            BluetoothChip
            Material
            ScreenResolution
            ScreenSize
            StandBy
            Waterproof
          }
        }
      }
    `,
    variables: {
      id: id,
    },
  });

  return {
    props: {
      products: data.products,
      product: data.product,
    },
  };
}

