import { ApolloClient, InMemoryCache, gql } from '@apollo/client';
import Head from "next/head";
import Catalogue from "@/components/Catalogue";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.css";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>quartz. watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className="NavBar" products={products} />
        <Catalogue products={products} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const client = new ApolloClient({
    uri: 'http://localhost:4000/graphql',
    cache: new InMemoryCache(),
  });

  const { data } = await client.query({
    query: gql`
      query GetProducts {
        products {
          id
          imageUrl
          name
          brandName
          groupId
          price {
            current {
              text
            }
          }
          features {
            BatteryCapacity
            BluetoothChip
            Material
            ScreenResolution
            ScreenSize
            StandBy
            Waterproof
          }
        }
      }
    `,
  });

  return {
    props: {
      products: data.products,
    },
  };
}
