import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Landing from "@/components/Landing";
import Product from "@/components/Product";
import Navbar from "@/components/Navbar";

export default function Home({ products, product }) {
  return (
    <>
      <Head>
        <title>quartz. watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className="NavBar" products={products} />
        <Product product={product} />
      </main>
    </>
  );
}

// runs at build time and gets all the ids that are passed on the params
export const getStaticPaths = async () => {
  //helps understand how many pages are needed to be generated
  const res = await fetch("http://localhost:8000/products/");
  const data = await res.json();

  // map data to an array of path objects with params (id)
  const paths = data.map((item) => {
    return {
      params: { id: item.id.toString() },
    };
  });

  return {
    paths, //builds a page for each id generated
    fallback: false, //fallback pages
  };
};

export const getStaticProps = async (context) => {
  try {
    const id = context.params.id;
    // Get the filter value from the context
    const res = await fetch("http://localhost:8000/products/" + id);
    const product = await res.json();

    const response = await fetch("http://localhost:8000/products/");
    const products = await response.json();
    return {
      props: {
        products,
        product,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        products,
        product,
      },
      revalidate: 60,
    };
  }
};
