import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Landing from "@/components/Landing";
import Products from "@/components/Products";
import Navbar from "@/components/Navbar";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>quartz. watches</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar className="NavBar" products={products} />
        <Landing />
        <Products products={products} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  try {
    // Get the filter value from the context
    // const filterValue = context.params?.filter ?? "";
    const res = await fetch("http://localhost:8000/products/");
    const products = await res.json();
    // const products = data.filter((item) => item.groupId == "kids");
    // console.log(filterValue);
    // console.log(data);
    return {
      props: {
        products,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        products,
      },
      revalidate: 60,
    };
  }
}
